import { Router } from 'express';
import { createOrder, listOrders, updateOrder } from '../controllers/orderController';
import { authMiddleware } from '../middlewares/authMiddleware';
import { validationHandler } from '../middlewares/validationHandler';
import { asyncHandler } from '../utils/asyncHandler';
import { idParam } from '../validators/common';
import { orderValidation } from '../validators/orderValidators';
import { orderStatusValidation } from '../validators/orderStatusValidator';
const router = Router();
router.post('/', orderValidation, validationHandler, asyncHandler(createOrder));
router.get('/', authMiddleware, asyncHandler(listOrders));
router.put('/:id', authMiddleware, idParam, orderStatusValidation, validationHandler, asyncHandler(updateOrder));
export default router;