import { Router } from 'express';
import { createService, deleteService, listServices, updateService } from '../controllers/serviceController';
import { authMiddleware } from '../middlewares/authMiddleware';
import { validationHandler } from '../middlewares/validationHandler';
import { asyncHandler } from '../utils/asyncHandler';
import { idParam } from '../validators/common';
import { serviceValidation } from '../validators/serviceValidators';
import { uploadImage } from '../middlewares/upload';
const router = Router();
router.get('/', asyncHandler(listServices));
router.post('/', authMiddleware, uploadImage, serviceValidation, validationHandler, asyncHandler(createService));
router.put('/:id', authMiddleware, uploadImage, idParam, serviceValidation, validationHandler, asyncHandler(updateService));
router.delete('/:id', authMiddleware, idParam, validationHandler, asyncHandler(deleteService));
export default router;