'use client';

import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import { apiRequest, ApiError, Product } from '@/lib/api';
import { clearAdminToken, getAdminToken } from '@/lib/adminAuth';
import { useRouter } from 'next/navigation';

type Form = { name: string; slug: string; price: string; description: string; fullDescription: string; image: File | null; imagePreview: string; stock: string; isNew: boolean };
const blank: Form = { name: '', slug: '', price: '', description: '', fullDescription: '', image: null, imagePreview: '', stock: '0', isNew: false };

export default function AdminProductsPage() {
  const router = useRouter();
  const [items, setItems] = useState<Product[]>([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  function handleError(requestError: unknown) { if (requestError instanceof ApiError && requestError.statusCode === 401) { clearAdminToken(); router.replace('/admin/login'); return; } setError(requestError instanceof ApiError ? requestError.message : 'Something went wrong. Please try again.'); }
  async function load() { try { setItems(await apiRequest<Product[]>('/products')); } catch (requestError) { handleError(requestError); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  function selectImage(event: ChangeEvent<HTMLInputElement>) { const image = event.target.files?.[0] ?? null; setForm((current) => ({ ...current, image, imagePreview: image ? URL.createObjectURL(image) : current.imagePreview })); }
  function edit(item: Product) { setEditing(item._id); setForm({ name: item.name, slug: item.slug, price: String(item.price), description: item.description, fullDescription: item.fullDescription, image: null, imagePreview: item.image?.url ?? '', stock: String(item.stock), isNew: item.isNew }); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const token = getAdminToken(); if (!token) return router.replace('/admin/login'); if (!editing && !form.image) return setError('Please select a product image.'); setSaving(true); setError(''); try { const body = new FormData(); body.append('name', form.name); body.append('slug', form.slug); body.append('price', form.price); body.append('description', form.description); body.append('fullDescription', form.fullDescription || form.description); body.append('stock', form.stock); body.append('isNew', String(form.isNew)); if (form.image) body.append('image', form.image); await apiRequest(editing ? `/products/${editing}` : '/products', { method: editing ? 'PUT' : 'POST', body }, token); setForm(blank); setEditing(null); await load(); } catch (requestError) { handleError(requestError); } finally { setSaving(false); } }
  async function remove(id: string) { const token = getAdminToken(); if (!token) return router.replace('/admin/login'); try { await apiRequest(`/products/${id}`, { method: 'DELETE' }, token); await load(); } catch (requestError) { handleError(requestError); } }
  return <section className="admin-page"><div className="admin-page-heading"><div><p className="eyebrow">Catalog</p><h1>Products</h1><p className="admin-description">Manage home remedies and their availability.</p></div><button className="admin-primary bg-gradient-gold" onClick={() => { setEditing(editing !== null ? null : ''); setForm(blank); }} type="button">{editing !== null ? 'Cancel' : 'Add product'} <span aria-hidden="true">+</span></button></div>{error && <p className="admin-error" role="alert">{error}</p>}{loading ? <div className="admin-loading">Loading products...</div> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>New</th><th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item._id}><td><strong>{item.name}</strong><small>{item.description}</small></td><td>PKR {item.price.toLocaleString()}</td><td>{item.stock}</td><td>{item.isNew ? 'Yes' : 'No'}</td><td><div className="admin-actions"><button onClick={() => edit(item)} type="button">Edit</button><button className="danger" onClick={() => void remove(item._id)} type="button">Delete</button></div></td></tr>)}</tbody></table></div>}{editing !== null && <form className="admin-editor" onSubmit={save}><h2>{editing ? 'Edit product' : 'Add product'}</h2><Field label="Name" value={form.name} onChange={(value) => setForm({ ...form, name: value })} /><Field label="Slug" value={form.slug} onChange={(value) => setForm({ ...form, slug: value })} /><Field label="Price" value={form.price} onChange={(value) => setForm({ ...form, price: value })} /><Field label="Description" value={form.description} onChange={(value) => setForm({ ...form, description: value })} /><Field label="Full description" value={form.fullDescription} onChange={(value) => setForm({ ...form, fullDescription: value })} /><Field label="Stock" value={form.stock} onChange={(value) => setForm({ ...form, stock: value })} /><label>Image<input accept="image/jpeg,image/png,image/webp" onChange={selectImage} required={!editing} type="file" /></label>{form.imagePreview && <img alt="Selected product preview" className="admin-image-preview" src={form.imagePreview} />}<label className="admin-check"><input checked={form.isNew} onChange={(event) => setForm({ ...form, isNew: event.target.checked })} type="checkbox" /> Mark as new</label><button className="admin-primary bg-gradient-gold" disabled={saving} type="submit">{saving ? 'Uploading...' : 'Save product'}</button></form>}</section>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label>{label}<input required onChange={(event) => onChange(event.target.value)} value={value} /></label>; }
